title: "Saml SP"
tagline: "SSO for CraftCMS v3"
description: "A Saml 2.0 Service Provider Plugin for CraftCMS v3."
logo: "https://cdn.flipboxdigital.com/logo/saml-sp.svg"
url: "https://flipboxfactory.github.io/saml-sp"
theme: "https://theme.flipboxfactory.com/1.1.6"
google_analytics_tracking_id: "XX-XXXXXXXX-X"